//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKH_NEW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapDoDeTai
    {
        public string MaCapDoDeTai { get; set; }
        public string TenCapDoDeTai { get; set; }
    }
}
