//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKH_NEW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LyLichKhoaHoc_NgoaiNgu
    {
        public int IDLyLichKhoaHoc { get; set; }
        public int IDNgoaiNgu { get; set; }
        public string Nghe { get; set; }
        public string Noi { get; set; }
        public string Viet { get; set; }
        public string Doc { get; set; }
    
        public virtual LyLichKhoaHoc LyLichKhoaHoc { get; set; }
        public virtual NgoaiNgu NgoaiNgu { get; set; }
    }
}
