//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKH_NEW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LyLichKhoaHoc_Sach
    {
        public int IDSach { get; set; }
        public Nullable<int> IDLyLichKhoaHoc { get; set; }
        public string TenSach { get; set; }
        public string NhaXuatBan { get; set; }
        public string NgayXuatBan { get; set; }
        public string ChuBien { get; set; }
        public string ThamGia { get; set; }
        public string GioNCKHQuyDoi { get; set; }
    
        public virtual LyLichKhoaHoc LyLichKhoaHoc { get; set; }
    }
}
