//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKH_NEW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LyLichKhoaHoc_QuaTrinhCongTac
    {
        public int IDQuaTrinhCongTac { get; set; }
        public Nullable<int> IDLyLichKhoaHoc { get; set; }
        public string TuNgay { get; set; }
        public string DenNgay { get; set; }
        public string NoiCongTac { get; set; }
        public string ChucVu { get; set; }
    
        public virtual LyLichKhoaHoc LyLichKhoaHoc { get; set; }
    }
}
