//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKH_NEW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LyLichKhoaHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LyLichKhoaHoc()
        {
            this.LyLichKhoaHoc_BaiBaoDang = new HashSet<LyLichKhoaHoc_BaiBaoDang>();
            this.LyLichKhoaHoc_ChuyenGiaoCongNghe = new HashSet<LyLichKhoaHoc_ChuyenGiaoCongNghe>();
            this.LyLichKhoaHoc_DangKyDeTaiNCKH = new HashSet<LyLichKhoaHoc_DangKyDeTaiNCKH>();
            this.LyLichKhoaHoc_DeTaiDaHoanThanh = new HashSet<LyLichKhoaHoc_DeTaiDaHoanThanh>();
            this.LyLichKhoaHoc_HoatDongKhac = new HashSet<LyLichKhoaHoc_HoatDongKhac>();
            this.LyLichKhoaHoc_HoiThao = new HashSet<LyLichKhoaHoc_HoiThao>();
            this.LyLichKhoaHoc_HuongDanNCKH = new HashSet<LyLichKhoaHoc_HuongDanNCKH>();
            this.LyLichKhoaHoc_NgoaiNgu = new HashSet<LyLichKhoaHoc_NgoaiNgu>();
            this.LyLichKhoaHoc_QuaTrinhCongTac = new HashSet<LyLichKhoaHoc_QuaTrinhCongTac>();
            this.LyLichKhoaHoc_QuaTrinhDaoTao = new HashSet<LyLichKhoaHoc_QuaTrinhDaoTao>();
            this.LyLichKhoaHoc_Sach = new HashSet<LyLichKhoaHoc_Sach>();
            this.LyLichKhoaHoc_Seminar = new HashSet<LyLichKhoaHoc_Seminar>();
            this.LyLichKhoaHoc_TinhHuongNghienCuu = new HashSet<LyLichKhoaHoc_TinhHuongNghienCuu>();
        }
    
        public int IDLyLichKhoaHoc { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public string NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string MaDonVi { get; set; }
        public string ChucVu { get; set; }
        public string HocVi { get; set; }
        public Nullable<int> NamCapHocVi { get; set; }
        public string HocHam { get; set; }
        public Nullable<int> NamPhongHocHam { get; set; }
        public string DiaChiCQ { get; set; }
        public string DiChiCaNhan { get; set; }
        public string DienThoaiCQ { get; set; }
        public string DienThoaiCaNhan { get; set; }
        public string EmailCQ { get; set; }
        public string EmailCaNhan { get; set; }
        public string UrlAnh { get; set; }
    
        public virtual DonVi DonVi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LyLichKhoaHoc_BaiBaoDang> LyLichKhoaHoc_BaiBaoDang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LyLichKhoaHoc_ChuyenGiaoCongNghe> LyLichKhoaHoc_ChuyenGiaoCongNghe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LyLichKhoaHoc_DangKyDeTaiNCKH> LyLichKhoaHoc_DangKyDeTaiNCKH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LyLichKhoaHoc_DeTaiDaHoanThanh> LyLichKhoaHoc_DeTaiDaHoanThanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LyLichKhoaHoc_HoatDongKhac> LyLichKhoaHoc_HoatDongKhac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LyLichKhoaHoc_HoiThao> LyLichKhoaHoc_HoiThao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LyLichKhoaHoc_HuongDanNCKH> LyLichKhoaHoc_HuongDanNCKH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LyLichKhoaHoc_NgoaiNgu> LyLichKhoaHoc_NgoaiNgu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LyLichKhoaHoc_QuaTrinhCongTac> LyLichKhoaHoc_QuaTrinhCongTac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LyLichKhoaHoc_QuaTrinhDaoTao> LyLichKhoaHoc_QuaTrinhDaoTao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LyLichKhoaHoc_Sach> LyLichKhoaHoc_Sach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LyLichKhoaHoc_Seminar> LyLichKhoaHoc_Seminar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LyLichKhoaHoc_TinhHuongNghienCuu> LyLichKhoaHoc_TinhHuongNghienCuu { get; set; }
    }
}
