//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKH_NEW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LyLichKhoaHoc_HoiThao
    {
        public int IDHoiThao { get; set; }
        public Nullable<int> IDLyLichKhoaHoc { get; set; }
        public string LoaiHoiThao { get; set; }
        public string TenBaiBao { get; set; }
        public string TenTacGia { get; set; }
        public string TenHoiNghi { get; set; }
        public string CapToChuc { get; set; }
        public string NgayToChuc { get; set; }
        public string SoHieuISBN { get; set; }
        public string SanPhamCuaDeTai { get; set; }
        public string GioNCKHQuyDoi { get; set; }
    
        public virtual LyLichKhoaHoc LyLichKhoaHoc { get; set; }
    }
}
