//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKH_NEW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LyLichKhoaHoc_HuongDanNCKH
    {
        public int IDHuongDanNCKH { get; set; }
        public Nullable<int> IDLyLichKhoaHoc { get; set; }
        public string TenDeTai { get; set; }
        public string KeQuaKhoaDanhGia { get; set; }
        public string KeQuaTruongDanhGia { get; set; }
        public string GiaiThuong { get; set; }
        public string TuNgay { get; set; }
        public string DenNgay { get; set; }
        public string GhiChu { get; set; }
        public string GioNCKHQuyDoi { get; set; }
    
        public virtual LyLichKhoaHoc LyLichKhoaHoc { get; set; }
    }
}
