//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKH_NEW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LyLichKhoaHoc_DeTaiDaHoanThanh
    {
        public int IDDeTaiDaHoanThanh { get; set; }
        public Nullable<int> IDLyLichKhoaHoc { get; set; }
        public string CapDoDeTai { get; set; }
        public string TenDeTai { get; set; }
        public string MaSoVaCapQuanLy { get; set; }
        public string TuNgay { get; set; }
        public string DenNgay { get; set; }
        public string KinhPhi { get; set; }
        public string ChuNhiem { get; set; }
        public string ThamGia { get; set; }
        public string NgayNghiemThu { get; set; }
        public string KetQua { get; set; }
        public string GioNCKHQuyDoi { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual LyLichKhoaHoc LyLichKhoaHoc { get; set; }
    }
}
