//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKH_NEW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LyLichKhoaHoc_QuaTrinhDaoTao
    {
        public int IDQuaTrinhDaoTao { get; set; }
        public Nullable<int> IDLyLichKhoaHoc { get; set; }
        public string BacDaoTao { get; set; }
        public string TuNgay { get; set; }
        public string DenNgay { get; set; }
        public string NoiDaoTao { get; set; }
        public string Nganh { get; set; }
        public string TenLuanAnTotNghiep { get; set; }
    
        public virtual LyLichKhoaHoc LyLichKhoaHoc { get; set; }
    }
}
