//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKH_NEW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NgoaiNgu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NgoaiNgu()
        {
            this.LyLichKhoaHoc_NgoaiNgu = new HashSet<LyLichKhoaHoc_NgoaiNgu>();
        }
    
        public int IDNgoaiNgu { get; set; }
        public string Ngoaingu1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LyLichKhoaHoc_NgoaiNgu> LyLichKhoaHoc_NgoaiNgu { get; set; }
    }
}
